CREATE TABLE CUSTOMERS (id int primary key, firstname varchar(30),
    lastname varchar(30), ADDRESS VARCHAR(100));

CREATE TABLE ORDERS (ID INT primary key,
   PRODUCT_NAME VARCHAR(30),
   PRODUCT_PRICE FLOAT,
   DATE_ORDER DATE,
   ID_CUSTOMER INT,
   AMOUNT INT,
   FOREIGN KEY(ID_CUSTOMER) REFERENCES CUSTOMERS(ID) ON DELETE CASCADE);