SELECT C.FIRSTNAME,
       C.LASTNAME,
       O.PRODUCT_NAME
FROM ORDERS O
LEFT JOIN CUSTOMERS C ON C.ID = O.ID_CUSTOMER
UNION 
SELECT C.FIRSTNAME,
       C.LASTNAME,
       O.PRODUCT_NAME
FROM CUSTOMERS C
LEFT JOIN ORDERS O ON C.ID = O.ID_CUSTOMER
WHERE O.PRODUCT_NAME IS NULL
ORDER BY C.FIRSTNAME, C.LASTNAME, O.PRODUCT_NAME;