SELECT C.FIRSTNAME, C.LASTNAME, COUNT(*) 
FROM CUSTOMERS C, ORDERS O 
WHERE C.ID = O.ID_CUSTOMER
GROUP BY C.FIRSTNAME, C.LASTNAME;

SELECT C.FIRSTNAME, C.LASTNAME, SUM(O.PRODUCT_PRICE*O.AMOUNT) 
FROM CUSTOMERS C, ORDERS O
WHERE C.ID = O.ID_CUSTOMER
GROUP BY C.FIRSTNAME, C.LASTNAME;
