-- SELECT C.LASTNAME, C.FIRSTNAME
-- FROM CUSTOMERS C LEFT JOIN ORDERS O ON C.ID = O.ID_CUSTOMER
-- GROUP BY C.LASTNAME, C.FIRSTNAME 
-- HAVING O.PRODUCT_PRICE*O.AMOUNT = (SELECT MAX(PRODUCT_PRICE*AMOUNT) FROM ORDERS)
-- ORDER BY C.FIRSTNAME, C.LASTNAME;

-- SELECT C.LASTNAME, C.FIRSTNAME
-- FROM CUSTOMERS C, ORDERS O
-- WHERE C.ID = O.ID_CUSTOMER 
-- AND O.PRODUCT_PRICE*O.AMOUNT = (SELECT MAX(PRODUCT_PRICE*AMOUNT) FROM ORDERS)
-- GROUP BY C.LASTNAME, C.FIRSTNAME
-- ORDER BY C.FIRSTNAME, C.LASTNAME;

SELECT DISTINCT C.LASTNAME, C.FIRSTNAME
FROM CUSTOMERS C, ORDERS O
WHERE C.ID = O.ID_CUSTOMER 
AND O.PRODUCT_PRICE*O.AMOUNT = (SELECT MAX(PRODUCT_PRICE*AMOUNT) FROM ORDERS)
ORDER BY C.FIRSTNAME, C.LASTNAME;

